import { normalizeMonth } from './revenueUtils'

/**
 * Calculates all-time milestones from revenues, profiles, teams, and DIS reports.
 */
export function calculateMilestones(revenues, profiles, teams, disReports = []) {
  const teamMap = {}
  teams.forEach(t => {
    teamMap[t.id] = t.name
  })

  const profileMap = {}
  profiles.forEach(p => {
    profileMap[p.id] = p
  })

  // Filter out admins from individual records
  const nonAdminProfiles = profiles.filter(p => p.platform_role !== 'admin')
  const nonAdminIds = new Set(nonAdminProfiles.map(p => p.id))
  
  // Find team leads
  const teamLeadProfiles = profiles.filter(p => p.platform_role === 'teamlead')
  const teamLeadIds = new Set(teamLeadProfiles.map(p => p.id))

  // 1. Highest revenue member in a month (All-Time)
  // Group by (user_id, month)
  const userMonthRev = {}
  revenues.forEach(r => {
    if (!nonAdminIds.has(r.user_id)) return
    const month = normalizeMonth(r.revenue_month)
    const key = `${r.user_id}_${month}`
    userMonthRev[key] = (userMonthRev[key] || 0) + Number(r.amount || 0)
  })

  let maxMemberInMonth = { amount: 0, userName: 'N/A', teamName: 'N/A', month: 'N/A' }
  Object.entries(userMonthRev).forEach(([key, amount]) => {
    const [userId, month] = key.split('_')
    if (amount > maxMemberInMonth.amount) {
      const profile = profileMap[userId]
      const userName = profile ? `${profile.first_name} ${profile.last_name}` : 'Unknown'
      const teamName = profile && profile.team_id ? teamMap[profile.team_id] : 'No Team'
      maxMemberInMonth = { amount, userName, teamName, month, userId }
    }
  })

  // 2. Highest revenue in a month by team (All-Time)
  // Group by (team_id, month)
  const teamMonthRev = {}
  revenues.forEach(r => {
    if (!r.team_id) return
    const month = normalizeMonth(r.revenue_month)
    const key = `${r.team_id}_${month}`
    teamMonthRev[key] = (teamMonthRev[key] || 0) + Number(r.amount || 0)
  })

  let maxTeamInMonth = { amount: 0, teamName: 'N/A', month: 'N/A' }
  Object.entries(teamMonthRev).forEach(([key, amount]) => {
    const [teamId, month] = key.split('_')
    if (amount > maxTeamInMonth.amount) {
      const teamName = teamMap[teamId] || 'Unknown Team'
      maxTeamInMonth = { amount, teamName, month, teamId }
    }
  })

  // 3. All-time highest revenue in a month combining all teams
  // Group by month
  const companyMonthRev = {}
  revenues.forEach(r => {
    const month = normalizeMonth(r.revenue_month)
    companyMonthRev[month] = (companyMonthRev[month] || 0) + Number(r.amount || 0)
  })

  let maxCompanyInMonth = { amount: 0, month: 'N/A' }
  Object.entries(companyMonthRev).forEach(([month, amount]) => {
    if (amount > maxCompanyInMonth.amount) {
      maxCompanyInMonth = { amount, month }
    }
  })

  // 4. All-time highest revenue team lead in one month
  // Group by (user_id, month) where user is team lead
  const leadMonthRev = {}
  revenues.forEach(r => {
    if (!teamLeadIds.has(r.user_id)) return
    const month = normalizeMonth(r.revenue_month)
    const key = `${r.user_id}_${month}`
    leadMonthRev[key] = (leadMonthRev[key] || 0) + Number(r.amount || 0)
  })

  let maxLeadInMonth = { amount: 0, userName: 'N/A', teamName: 'N/A', month: 'N/A' }
  Object.entries(leadMonthRev).forEach(([key, amount]) => {
    const [userId, month] = key.split('_')
    if (amount > maxLeadInMonth.amount) {
      const profile = profileMap[userId]
      const userName = profile ? `${profile.first_name} ${profile.last_name}` : 'Unknown'
      const teamName = profile && profile.team_id ? teamMap[profile.team_id] : 'No Team'
      maxLeadInMonth = { amount, userName, teamName, month, userId }
    }
  })

  // ── EXTRA SUGGESTIONS ──

  // 5. Largest Deal Ever Closed (Single client revenue entry)
  let maxSingleDeal = { amount: 0, clientName: 'N/A', userName: 'N/A', teamName: 'N/A', month: 'N/A' }
  revenues.forEach(r => {
    const amount = Number(r.amount || 0)
    if (amount > maxSingleDeal.amount) {
      const profile = profileMap[r.user_id]
      const userName = profile ? `${profile.first_name} ${profile.last_name}` : 'Unknown'
      const teamName = r.team_id ? teamMap[r.team_id] : (profile && profile.team_id ? teamMap[profile.team_id] : 'No Team')
      maxSingleDeal = {
        amount,
        clientName: r.client_name || 'Unknown Client',
        userName,
        teamName,
        month: normalizeMonth(r.revenue_month)
      }
    }
  })

  // 6. Most Leads Generated by a Member in a Single Month (All-Time)
  // Group by (user_id, month) in disReports
  const leadGenMonth = {}
  disReports.forEach(r => {
    if (!r.report_date) return
    const month = normalizeMonth(r.report_date)
    const key = `${r.user_id}_${month}`
    leadGenMonth[key] = (leadGenMonth[key] || 0) + Number(r.positive_leads || 0)
  })

  let maxLeadsInMonth = { count: 0, userName: 'N/A', teamName: 'N/A', month: 'N/A' }
  Object.entries(leadGenMonth).forEach(([key, count]) => {
    const [userId, month] = key.split('_')
    if (count > maxLeadsInMonth.count) {
      const profile = profileMap[userId]
      const userName = profile ? `${profile.first_name} ${profile.last_name}` : 'Unknown'
      const teamName = profile && profile.team_id ? teamMap[profile.team_id] : 'No Team'
      maxLeadsInMonth = { count, userName, teamName, month, userId }
    }
  })

  return {
    maxMemberInMonth,
    maxTeamInMonth,
    maxCompanyInMonth,
    maxLeadInMonth,
    maxSingleDeal,
    maxLeadsInMonth
  }
}
